# Generated by Django 5.2.6 on 2025-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legacybox",
            name="is_released",
            field=models.BooleanField(default=False),
        ),
    ]
