# Generated by Django 5.2.6 on 2025-09-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0002_add_is_released"),
    ]

    operations = [
        migrations.AddField(
            model_name="memory",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="memories/"
            ),
        ),
        migrations.AddField(
            model_name="memory",
            name="memory_type",
            field=models.CharField(
                choices=[
                    ("LETTER", "Letter"),
                    ("PHOTO", "Photo"),
                    ("VIDEO", "Video"),
                ],
                default="LETTER",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
