# Generated by Django 5.2.6 on 2025-09-21 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core_api", "0003_add_memory_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacybox",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Keyholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyholders",
                        to="core_api.legacybox",
                    ),
                ),
            ],
            options={
                "unique_together": {("box", "email")},
            },
        ),
    ]
